---
title: 'Chimpanzee Faceshape (Male vs. Female) Bayesian Procrusts:'
author: "Debashis Chatterjee"
date: "11/11/2020"
output: pdf_document
---

```{r}
require(shapes)
data(gorf.dat)
data(gorm.dat)

ogf=gf=gorf.dat
ogm=gm=gorm.dat
```

```{r}
plotshapes(gm[,,1],joinline=c(1,6,7,8,2,3,4,5,1), col=1:8, symbol=1:8)
polygon(gm[,1,1],gm[,2,1])
```

```{r}

```


```{r}
dim(ogm)
```


```{r}
sortcoldat=function(dat,seq)
{dat[,,]=dat[seq,,]
  return(dat)
}
```

```{r}
o.gf=ogf=sortcoldat(ogf,c(1,6,7,8,2,3,4,5))
o.gm=ogm=sortcoldat(ogm,c(1,6,7,8,2,3,4,5))
```

```{r}

for(k in 1:dim(ogf)[3])
{
  o.gf[,,k] <- rotonto(ogf[,,1],ogf[,,k],scale=T)$yrot 
}

for(k in 1:dim(ogm)[3])
{
  o.gm[,,k] <- rotonto(ogm[,,1],ogm[,,k],scale=T)$yrot 
}

```

```{r}
plot(c(min(o.gm[,1,])-30, 100+max(o.gm[,1,])), c(min(o.gm[,2,])-30, max(o.gm[,2,])+30), type = "n", main="Raw Data-plot of Apes: male & female", xlab="x",ylab="y")
#plotshapes(gm[,,1],joinline=c(1,6,7,8,2,3,4,5,1), col=1:8, symbol=1:8)

polygon(o.gm[,1,1],o.gm[,2,1],density=0, col="skyblue", border="blue")
points(o.gm[,1,1],o.gm[,2,1], col="blue",pch=1:8)
polygon(o.gf[,1,1],o.gf[,2,1],density=0, col="pink", border="red")
points(o.gf[,1,1],o.gf[,2,1], col="red",pch=1:8)
```

```{r}
require(BPviGM1)
apem10000.10=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gm[,,1:10],10000)
```
```{r}
PPLOTpostvar2D(apem10000.10, 1000)
```



```{r}
apem10000.20=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gm[,,1:20],10000)
```
```{r}
PPLOTpostvar2D(apem10000.20, 1000)
```

```{r}
apem10000.30=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gm[,,],10000)
```

```{r}
PPLOTpostvar2D(apem10000.30, 1000)
```


```{r}
apef10000.10=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gf[,,1:10],10000)
```
```{r}
PPLOTpostvar2D(apef10000.10, 1000)
```

```{r}
apef10000.20=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gf[,,1:20],10000)
```
```{r}
PPLOTpostvar2D(apef10000.20, 1000)
```


```{r}
apef10000.30=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gf,10000)
```

```{r}
PPLOTpostvar2D(apef10000.30, 1000)
```

```{r}

#plot(density(ress_10[1001:10000,2]), xlim=c(0,8),ylim=c(0,5),col="red",ylab="density (with vague prior)", xlab="Sample")
plot(density(apem10000.10), xlim=c(1,6),ylim=c(0,4),col="skyblue", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of APE (male)")~~tilde(sigma)~~("+ uniform prior"))))
#abline(v=theta, col="black",lwd=2, lty=1)
abline(v=mean(apem10000.30), col="darkblue",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.30), ylim=c(0,12),col="blueviolet")

legend("topleft",cex=0.6, c("n=10","n=20","n=30", expression(("(Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("skyblue","blue","blueviolet","darkblue"), lwd = c(1,1,1,1))
```




```{r}

#plot(density(ress_10[1001:10000,2]), xlim=c(0,8),ylim=c(0,5),col="red",ylab="density (with vague prior)", xlab="Sample")
plot(density(apef10000.10), xlim=c(1,6),ylim=c(0,4),col="orange", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of APE (female)")~~tilde(sigma)~~("+ uniform prior"))))
#abline(v=theta, col="black",lwd=2, lty=1)
abline(v=mean(apef10000.30), col="red4",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apef10000.20), ylim=c(0,12),col="hotpink")
lines(density(apef10000.30), ylim=c(0,12),col="red")

legend("topright",cex=0.6, c("n=10","n=20","n=30", expression(("(Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("orange","hotpink","red","red4"), lwd = c(1,1,1,1))
```



```{r}
#COMBINED PLOT 

#plot(density(ress_10[1001:10000,2]), xlim=c(0,8),ylim=c(0,5),col="red",ylab="density (with vague prior)", xlab="Sample")
plot(density(apef10000.10[1000:10000]), xlim=c(1,7),ylim=c(0,5),col="orange", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of Variance: Gorilla (Male vs. female)")~~tilde(sigma)~~("+ uniform prior"))))
#abline(v=theta, col="black",lwd=2, lty=1)
abline(v=mean(apef10000.30), col="red4",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apef10000.20), ylim=c(0,12),col="hotpink")
lines(density(apef10000.30), ylim=c(0,12),col="red")

legend("topleft",cex=0.6,title="Ape (Female)", c("n=10","n=20","n=30", expression(("Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("orange","hotpink","red","red4"), lwd = c(1,1,1,1))
abline(v=mean(apem10000.30), col="darkblue",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.30), ylim=c(0,12),col="blue4")
lines(density(apem10000.10[1000:10000]), ylim=c(0,12),col="skyblue");
legend("topright",cex=0.6,title="Ape (Male)", c("n=10","n=20","n=30", expression(("Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("skyblue","blue","blue4","darkblue"), lwd = c(1,1,1,1))
grid()


```
