---
title: "Classical Shape Ana (Draft)"
author: "Debashis Chatterjee"
date: "10/19/2020"
output: pdf_document
---






```{r}
require(shapes)
require(Morpho)
```

```{r}
data(apes)
proc <- procSym(apes$x)

```
```{r}
procSym

```

```{r}
par(mfrow=c(1,2))
plotshapes(apes$x[,,apes$group=="gorf"],symbol="f")
plotshapes(apes$x[,,apes$group=="gorm"],symbol="m")
```

```{r}
data(gorf.dat)
data(gorm.dat)
bookf<-bookstein2d(gorf.dat)
bookm<-bookstein2d(gorm.dat)
plotshapes(bookf$mshape,bookm$mshape,joinline=c(1,6,7,8,2,3,4,5,1))
```

```{r}
bookstein2d
```

```{r}
data(brains)
# plot first three brains
shapes3d(brains$x[,,1:3])
```


```{r}
data(digit3.dat)
k<-dim(digit3.dat)[1]
n<-dim(digit3.dat)[3]
plotshapes(digit3.dat,joinline=c(1:13))
```


```{r}
require(shapes)
data(gorf.dat)
data(gorm.dat)

ogf=gf=gorf.dat
ogm=gm=gorm.dat
```

```{r}
plotshapes(gm[,,1],joinline=c(1,6,7,8,2,3,4,5,1), col=1:8, symbol=1:8)
polygon(gm[,1,1],gm[,2,1])
```

```{r}

```


```{r}
dim(ogm)
```


```{r}
sortcoldat=function(dat,seq)
{dat[,,]=dat[seq,,]
  return(dat)
}
```

```{r}
o.gf=ogf=sortcoldat(ogf,c(1,6,7,8,2,3,4,5))
o.gm=ogm=sortcoldat(ogm,c(1,6,7,8,2,3,4,5))
```

```{r}

for(k in 1:dim(ogf)[3])
{
  o.gf[,,k] <- rotonto(ogf[,,1],ogf[,,k],scale=T)$yrot 
}

for(k in 1:dim(ogm)[3])
{
  o.gm[,,k] <- rotonto(ogm[,,1],ogm[,,k],scale=T)$yrot 
}

```

```{r}
plot(c(min(o.gm[,1,])-30, 100+max(o.gm[,1,])), c(min(o.gm[,2,])-30, max(o.gm[,2,])+30), type = "n", main="Raw Data-plot of Apes: male & female", xlab="x",ylab="y")
#plotshapes(gm[,,1],joinline=c(1,6,7,8,2,3,4,5,1), col=1:8, symbol=1:8)

polygon(o.gm[,1,1],o.gm[,2,1],density=0, col="skyblue", border="blue")
points(o.gm[,1,1],o.gm[,2,1], col="blue",pch=1:8)
polygon(o.gf[,1,1],o.gf[,2,1],density=0, col="pink", border="red")
points(o.gf[,1,1],o.gf[,2,1], col="red",pch=1:8)
```

```{r}
require(BPviGM1)
apem10000.10=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gm[,,1:10],10000)
```
```{r}
PPLOTpostvar2D(apem10000.10, 1000)
```



```{r}
apem10000.20=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gm[,,1:20],10000)
```
```{r}
PPLOTpostvar2D(apem10000.20, 1000)
```

```{r}
apem10000.30=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gm[,,],10000)
```

```{r}
PPLOTpostvar2D(apem10000.30, 1000,colu="blue")
```


```{r}
apef10000.10=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gf[,,1:10],10000)
```
```{r}
PPLOTpostvar2D(apef10000.10, 1000)
```

```{r}
apef10000.20=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gf[,,1:20],10000)
```
```{r}
PPLOTpostvar2D(apef10000.20, 1000)
```


```{r}
apef10000.30=MCMCpostPsample2D(1.5,
rep(0.5,1),o.gf,10000)
```

```{r}
PPLOTpostvar2D(apef10000.30, 1000,colu="red")
```

```{r}

#plot(density(ress_10[1001:10000,2]), xlim=c(0,8),ylim=c(0,5),col="red",ylab="density (with vague prior)", xlab="Sample")
plot(density(apem10000.10), xlim=c(1,6),ylim=c(0,4),col="skyblue", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of APE (male)")~~tilde(sigma)~~("+ uniform prior"))))
#abline(v=theta, col="black",lwd=2, lty=1)
abline(v=mean(apem10000.30), col="darkblue",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.30), ylim=c(0,12),col="blueviolet")

legend("topleft",cex=0.6, c("n=10","n=20","n=30", expression(("(Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("skyblue","blue","blueviolet","darkblue"), lwd = c(1,1,1,1))
```




```{r}

#plot(density(ress_10[1001:10000,2]), xlim=c(0,8),ylim=c(0,5),col="red",ylab="density (with vague prior)", xlab="Sample")
plot(density(apef10000.10), xlim=c(1,6),ylim=c(0,4),col="orange", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of APE (female)")~~tilde(sigma)~~("+ uniform prior"))))
#abline(v=theta, col="black",lwd=2, lty=1)
abline(v=mean(apef10000.30), col="red4",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apef10000.20), ylim=c(0,12),col="hotpink")
lines(density(apef10000.30), ylim=c(0,12),col="red")

legend("topright",cex=0.6, c("n=10","n=20","n=30", expression(("(Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("orange","hotpink","red","red4"), lwd = c(1,1,1,1))
```



```{r}
#COMBINED PLOT 

#plot(density(ress_10[1001:10000,2]), xlim=c(0,8),ylim=c(0,5),col="red",ylab="density (with vague prior)", xlab="Sample")
plot(density(apef10000.10[1000:10000]), xlim=c(1,7),ylim=c(0,5),col="orange", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of Variance: Gorilla (Male vs. female)")~~tilde(sigma)~~("+ uniform prior"))))
#abline(v=theta, col="black",lwd=2, lty=1)
abline(v=mean(apef10000.30), col="red4",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apef10000.20), ylim=c(0,12),col="hotpink")
lines(density(apef10000.30), ylim=c(0,12),col="red")

legend("topleft",cex=0.6,title="Ape (Female)", c("n=10","n=20","n=30", expression(("Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("orange","hotpink","red","red4"), lwd = c(1,1,1,1))
abline(v=mean(apem10000.30), col="darkblue",lwd=2, lty=3)
#lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.20), ylim=c(0,12),col="blue")
lines(density(apem10000.30), ylim=c(0,12),col="blue4")
lines(density(apem10000.10[1000:10000]), ylim=c(0,12),col="skyblue");
legend("topright",cex=0.6,title="Ape (Male)", c("n=10","n=20","n=30", expression(("Bayes Estimate of ")~~tilde(sigma))), lty = c(1,1,1,3), col = c("skyblue","blue","blue4","darkblue"), lwd = c(1,1,1,1))
grid()


```

```{r}
tr5s=tr5=fivetr;
for(i in 1:dim(fivetr)[3])
{
  tr5s[,,i]=scale(tr5[,,i])
}

tr5s.10000=MCMCpostPsample2D(1.5,
rep(0.5,1),tr5s,10000)
```
```{r}
tr5sR=tr5R=fivetrR;
for(i in 1:dim(fivetrR)[3])
{
  tr5sR[,,i]=scale(tr5R[,,i])
}

tr5sR.10000=MCMCpostPsample2D(1.5,
rep(0.5,1),tr5sR,10000)
```

```{r}
PPLOTpostvar2D(tr5sR.10000, 1000)
```

```{r}
#COMBINED PLOT 

#plot(density(ress_10[1001:10000,2]), xlim=c(0,8),ylim=c(0,5),col="red",ylab="density (with vague prior)", xlab="Sample")
plot(density(tr5s.10000[1000:10000]), xlim=c(0.5,1.45),ylim=c(0,5.5),col="tomato", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of Variance:  of Random triangle")~~tilde(sigma)~~("+ uniform prior"))))
abline(v=mean(tr5s.10000), col="black",lwd=2, lty=3)
#abline(v=mean(apef10000.30), col="red4",lwd=2, lty=3)

legend("topright",cex=0.8, c("n=5", expression(("Bayes Estimate of ")~~tilde(sigma))), lty = c(1,3), col = c("tomato","black"), lwd = c(1,1))
grid()
```

```{r}

plot(density(tr5sR.10000[1000:10000]), xlim=c(0.0,0.8),ylim=c(0,12.5),col="blue", xlab=expression(("Bayes Estimate of ")~~tilde(sigma)),ylab="MCMC Posterior Sigma Density",cex.main=1,main=expression(paste(bold("MCMC  posterior of Variance:  of Random triangle")~~tilde(sigma)~~("+ uniform prior"))))
abline(v=mean(tr5sR.10000[1000:10000]), col="black",lwd=2, lty=3)
#abline(v=mean(apef10000.30), col="red4",lwd=2, lty=3)

legend("topright",cex=0.8, c("n=5", expression(("Bayes Estimate of ")~~tilde(sigma))), lty = c(1,3), col = c("tomato","black"), lwd = c(1,1))
grid()
```



```{r}
ape5000=MCMCpostPsample2D(1.5,
rep(0.1,1),myData,5000)
```

```{r}
plotshapes(apes$x[,,1], apes$x[,,2],joinline=c(1,6,7,8,2,3,4,5,1), col=1:8, symbol=1:8)
```

```{r}
make.mvn <- function(mean, vcv) {
  logdet <- as.numeric(determinant(vcv, TRUE)$modulus)
  tmp <- length(mean) * log(2 * pi) + logdet
  vcv.i <- solve(vcv)

  function(x) {
    dx <- x - mean
    exp(-(tmp + rowSums((dx %*% vcv.i) * dx))/2)
  }
}
```

```{r}
plot(c(-10, 30), c(-12,10), type = "n", main=" Simulated RawData: 1000 Random convex & concave Quadrilaterals",cex.main=0.98, xlab="x",ylab="y")

polygon(cvq[,1,1],cvq[,2,1],density=0, col="pink", border="red", lwd=2)
for(k in 1:1000)
{
  polygon(cvq[,1,k],cvq[,2,k],density=0, col="pink", border=alpha(rgb(1,0,0), 0.018), lty=5, lwd=1)
}

polygon(ccq[,1,1],ccq[,2,1],density=0, col="blue", border="blue", lwd=2)
for(k in 1:1000)
{
  polygon(ccq[,1,k],ccq[,2,k],density=0, col="green", border=alpha(rgb(0,0,1), 0.018), lty=2, lwd=1)
}


legend("bottomright", legend=c("1000 convex Quadrilaterals, true sigma=1.5", "1000 concave quadrilaterals, true sigma=0.8"),
       col=c("red", "blue"), lty=c(1,1), cex=0.5,
       title="Object shape types", text.font=4, bg='white')

```


```{r}
muu=matrix(rep(1,6),3,2)
for(i in 1:3)
{
  muu[i,]=tr5s[i,,1]
}
```


```{r}
muuR=matrix(rep(1,6),3,2)
for(i in 1:3)
{
  muuR[i,]=fivetrR[i,,1]
}
```


```{r}
muuRV=matrix(rep(1,8),4,2)
for(i in 1:4)
{
  muuRV[i,]=cvq[i,,1]
}
```



```{r}
muuRC=matrix(rep(1,8),4,2)
for(i in 1:4)
{
  muuRC[i,]=ccq[i,,1]
}
```


```{r}
mu=matrix(rep(1,16),8,2)
for(i in c(1,6,7,8,2,3,4,5,1))
{
  mu[i,]=apes$x[i,,1]
}
```


```{r}
sigmaV=1.5
  vcvisoV=(sigmaV^2)*matrix(c(1,0,0,1),2,2)
  sigmaC=0.8
sigmaC=mean(tr5sR.10000[1000:10000])
  vcvisoC=(sigmaC^2)*matrix(c(1,0,0,1),2,2)
  
```






```{r}
sigma1=mean(tr5s.10000[1000:10000])
  vcviso1=(sigma1^2)*matrix(c(1,0,0,1),2,2)
  sigma2=mean(tr5sR.10000[1000:10000])
  vcviso2=(sigma2^2)*matrix(c(1,0,0,1),2,2)
  
```

```{r}
sigma=mean(tr5s.10000)
  vcviso=(sigma^2)*matrix(c(1,0,0,1),2,2)
  
```


```{r}
ff1=make.mvn(muu[1,],vcviso1)
ff2=make.mvn(muu[2,],vcviso1)
ff3=make.mvn(muu[3,],vcviso1)
```

```{r}
ffR1=make.mvn(muuR[1,],vcviso2)
ffR2=make.mvn(muuR[2,],vcviso2)
ffR3=make.mvn(muuR[3,],vcviso2)
```


```{r}
ffRV1=make.mvn(muuRV[1,],vcvisoV)
ffRV2=make.mvn(muuRV[2,],vcvisoV)
ffRV3=make.mvn(muuRV[3,],vcvisoV)
ffRV4=make.mvn(muuRV[4,],vcvisoV)
```


```{r}
ffRC1=make.mvn(muuRC[1,],vcvisoC)
ffRC2=make.mvn(muuRC[2,],vcvisoC)
ffRC3=make.mvn(muuRC[3,],vcvisoC)
ffRC4=make.mvn(muuRC[4,],vcvisoC)
```

```{r}
ffRV <- function(x)
    ffRV1(x) + ffRV2(x)+ffRV3(x)+ffRV4(x)
ffRC <- function(x)
    ffRC1(x) + ffRC2(x)+ffRC3(x)+ffRC4(x)
```

```{r}

x <- seq(-14, max(cvq[,1,1])+25.3, length=100)
y <- seq(min(cvq[,2,1])-3.6, max(cvq[,2,1])+3.6, length=100)
xy <- expand.grid(x=x, y=y)
zv <- matrix(apply(as.matrix(xy), 1, ffRV), length(x), length(y))
zc <- matrix(apply(as.matrix(xy), 1, ffRC), length(x), length(y))
image(x, y, zv, las=1)
contour(x, y, zv, col = "red1",add=TRUE, method= "simple", vfont = c("sans serif", "plain"), nlev = 10, lty = 4, xlab ="Posterior Sigma density contour",labcex = 0.6, drawlabels = TRUE)
contour(x, y, zc, col = "blue",add=TRUE, method= "simple", vfont = c("sans serif", "plain"), nlev = 10, lty = 4, xlab ="Posterior Sigma density contour",labcex = 0.3, drawlabels = TRUE)
title("Posterior Sigma density contour (Data: Convex Quadrilaterals)", font = 2,cex=0.6)
polygon(cvq[,1,1],cvq[,2,1],density=20, col="pink", border="red", lwd=2)
#polygon(rt2[,1],rt2[,2],density=20, col="green", border="forestgreen")
#polygon(rt3[,1],rt3[,2],density=40, col="blue1", border="blue2", angle = -90)
#polygon(rt4[,1],rt4[,2],density=20, col="orange", border="darkorange")
polygon(ccq[,1,1],ccq[,2,1],density=20, col="skyblue", border="blue3", lwd = 2)
#draw.ellipse(x= c(0), y= c(0), c(1), c(1), border = 'gray', lwd = 1, lty=3)
grid()
```


```{r}
ff <- function(x)
    ff1(x) + ff2(x)+ff3(x)
ffR <- function(x)
    ffR1(x) + ffR2(x)+ffR3(x)
```

```{r}
a=c(0,0);b=c(-1,1);c=c(2,1); t1=rbind(a,b,c);
d=c(3,1);e=c(4,4);f=c(5,1); t2=rbind(d,e,f);
g=c(-3,3);h=c(3,4);i=c(3,3); t3=rbind(g,h,i);
j=c(-4,1);k=c(-3,2);l=c(-3,1); t4=rbind(j,k,l);
m=c(8,0);n=c(6,6);o=c(4,0); t5=rbind(m,n,o);
rt1=scale(t1);
rt2=scale(t2);
rt3=scale(t3);
rt4=scale(t4);
rt5=scale(t5);
```

```{r}
require(shapes);require(Morpho);
a=c(0,0);b=c(-1,1);c=c(2,1); t1=rbind(a,b,c);
d=c(3,1);e=c(4,4);f=c(5,1); t2=rbind(d,e,f);
g=c(-3,3);h=c(3,4);i=c(3,3); t3=rbind(g,h,i);
j=c(-4,1);k=c(-3,2);l=c(-3,1); t4=rbind(j,k,l);
m=c(8,0);n=c(6,6);o=c(4,0); t5=rbind(m,n,o);
rrt1=rotonto(t1,t1,scale = T)$yrot;
rrt2=rotonto(t1,t2,scale = T)$yrot;
rrt3=rotonto(t1,t3,scale = T)$yrot;
rrt4=rotonto(t1,t4,scale = T)$yrot;
rrt5=rotonto(t1,t5,scale = T)$yrot;
```


```{r}

x <- seq(min(tr5s[,1,1])-1.3, max(tr5s[,1,1])+1.3, length=100)
y <- seq(min(tr5s[,2,1])-1.6, max(tr5s[,2,1])+1.6, length=100)
xy <- expand.grid(x=x, y=y)
z <- matrix(apply(as.matrix(xy), 1, ff), length(x), length(y))

image(x, y, z, las=1)
contour(x, y, z, col = "red1",add=TRUE, method= "simple", vfont = c("sans serif", "plain"), nlev = 10, lty = 4, xlab ="Posterior Sigma density contour",labcex = 0.6, drawlabels = TRUE)
title("Posterior Sigma density contour (Data: 5 triangles)", font = 4)
polygon(rt1[,1],rt1[,2],density=20, col="pink", border="red", lwd=2)
polygon(rt2[,1],rt2[,2],density=20, col="green", border="forestgreen")
polygon(rt3[,1],rt3[,2],density=40, col="blue1", border="blue2", angle = -90)
polygon(rt4[,1],rt4[,2],density=20, col="orange", border="darkorange")
polygon(rt5[,1],rt5[,2],density=20, col="yellow", border="gold3", lty = 2)
#draw.ellipse(x= c(0), y= c(0), c(1), c(1), border = 'gray', lwd = 1, lty=3)
```








```{r}
plot(c(-10, 30), c(-12,10), type = "n", main=" Simulated RawData: 1000 Random convex & concave Quadrilaterals",cex.main=0.98, xlab="x",ylab="y")

polygon(cvq[,1,1],cvq[,2,1],density=0, col="pink", border="red", lwd=2)
for(k in 1:1000)
{
  polygon(cvq[,1,k],cvq[,2,k],density=0, col="pink", border=alpha(rgb(1,0,0), 0.018), lty=5, lwd=1)
}

polygon(ccq[,1,1],ccq[,2,1],density=0, col="blue", border="blue", lwd=2)
for(k in 1:1000)
{
  polygon(ccq[,1,k],ccq[,2,k],density=0, col="green", border=alpha(rgb(0,0,1), 0.018), lty=2, lwd=1)
}


legend("bottomright", legend=c("1000 convex Quadrilaterals, true sigma=1.5", "1000 concave quadrilaterals, true sigma=0.8"),
       col=c("red", "blue"), lty=c(1,1), cex=0.5,
       title="Object shape types", text.font=4, bg='white')

```


```{r}
plot(c(-10, 30), c(-12,10), type = "n", main=" Simulated RawData: 1000 Random convex & concave Quadrilaterals",cex.main=0.98, xlab="x",ylab="y")

polygon(cvq[,1,1],cvq[,2,1],density=0, col="pink", border="red", lwd=2)
for(k in 1:1000)
{
  polygon(cvq[,1,k],cvq[,2,k],density=0, col="pink", border=alpha(rgb(1,0,0), 0.018), lty=5, lwd=1)
}

polygon(ccq[,1,1],ccq[,2,1],density=0, col="blue", border="blue", lwd=2)
for(k in 1:1000)
{
  polygon(ccq[,1,k],ccq[,2,k],density=0, col="green", border=alpha(rgb(0,0,1), 0.018), lty=2, lwd=1)
}


legend("bottomright", legend=c("1000 convex Quadrilaterals, true sigma=1.5", "1000 concave quadrilaterals, true sigma=0.8"),
       col=c("red", "blue"), lty=c(1,1), cex=0.5,
       title="Object shape types", text.font=4, bg='white')

```



```{r}

x <- seq(-2, max(tr5sR[,1,1])+2, length=100)
#y <- seq(min(tr5sR[,2,1])-2, max(tr5sR[,2,1])+2, length=100)
y <- seq(-1, 2, length=100)
xy <- expand.grid(x=x, y=y)
z <- matrix(apply(as.matrix(xy), 1, ffR), length(x), length(y))

image(x, y, z, las=1)
contour(x, y, z, col = "red1",add=TRUE, method= "simple", vfont = c("sans serif", "plain"), nlev = 10, lty = 4, xlab ="Posterior Sigma density contour",labcex = 0.6, drawlabels = TRUE)
title("Posterior Sigma density contour (Data: 5 triangles)", font = 4)
polygon(fivetrR[,1,1],fivetrR[,2,1],density=20, col="pink", border="red", lwd=2)
polygon(rrt2[,1],rrt2[,2],density=20, col="green", border="forestgreen")
polygon(rrt3[,1],rrt3[,2],density=40, col="blue1", border="blue2", angle = -90)
polygon(rrt4[,1],rrt4[,2],density=20, col="orange", border="darkorange")
polygon(rrt5[,1],rrt5[,2],density=20, col="yellow", border="gold3", lty = 2)
#draw.ellipse(x= c(0), y= c(0), c(1), c(1), border = 'gray', lwd = 1, lty=3)
```





```{r}
f1=make.mvn(mu[1,],vcviso)
f2=make.mvn(mu[2,],vcviso)
f3=make.mvn(mu[3,],vcviso)
f4=make.mvn(mu[4,],vcviso)
f5=make.mvn(mu[5,],vcviso)
f6=make.mvn(mu[6,],vcviso)
f7=make.mvn(mu[7,],vcviso)
f8=make.mvn(mu[8,],vcviso)

```

```{r}
f <- function(x)
    f1(x) + f2(x)+f3(x)+f4(x)+f5(x)+f6(x)+f7(x)+f8(x)
```


```{r}

x <- seq(-100, 200, length=300)
y <- seq(-100, 300, length=300)
xy <- expand.grid(x=x, y=y)
z <- matrix(apply(as.matrix(xy), 1, f), length(x), length(y))

image(x, y, z, las=1)
contour(x, y, z, add=TRUE)
```


```{r}
mu1 <- c(-1, 1)
mu2 <- c(2, -2)
vcv1 <- matrix(c(1, .25, .25, 1.5), 2, 2)
vcv2 <- matrix(c(2, -.5, -.5, 2), 2, 2)
f1 <- make.mvn(mu1, vcv1)
f2 <- make.mvn(mu2, vcv2)
f <- function(x)
    f1(x) + f2(x)

x <- seq(-5, 6, length=71)
y <- seq(-7, 6, length=61)
xy <- expand.grid(x=x, y=y)
z <- matrix(apply(as.matrix(xy), 1, f), length(x), length(y))

image(x, y, z, las=1)
contour(x, y, z, add=TRUE)
```



```{r}
plotshapes(apes$x[,,1],joinline=c(1,6,7,8,2,3,4,5,1))


```
```{r}
data(gorf.dat)
data(gorm.dat)
plotshapes(gorf.dat,gorm.dat,joinline=c(1,6,7,8,2,3,4,5,1))
```






```{r}

data(macm.dat)
data(macf.dat)
plotshapes(macm.dat,macf.dat)
```




```{r}
data(dna.dat)
plotshapestime3d(dna.dat)
```









